springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    urls:
      - name: ${SWAGGER_UI_URLS_0_NAME:mfs-ledger-service}
        url: ${SWAGGER_UI_URLS_0_URL:http://localhost:8081/v3/api-docs/mfs-ledger-service}
      - name: ${SWAGGER_UI_URLS_2_NAME:mfs-user-service}
        url: ${SWAGGER_UI_URLS_2_URL:http://localhost:8090/v3/api-docs/mfs-user-service}
      - name: ${SWAGGER_UI_URLS_3_NAME:mfs-third-party-service}
        url: ${SWAGGER_UI_URLS_3_URL:http://localhost:8090/v3/api-docs/mfs-third-party-service}
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: ${SERVER_PORT:8080}
---
spring:
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: MFS-LEDGER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/ledger-service/**
          filters:
            - RewritePath=/ledger-service/(?<path>.*), /${path}
        - id: MFS-USER-SERVICE
          uri: http://localhost:8090
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /${path}
        - id: MFS-THIRD-PARTY-SERVICE
          uri: http://localhost:8899
          predicates:
            - Path=/third-party-service/**
          filters:
            - RewritePath=/third-party-service/(?<path>.*), /${path}
